language: node_js
node_js:
  - '0.10'
env:
  secure: NOZ0gtICedpZXRErjjiC7JDe0noLPpnv2hRIjdi0ddA2An0aXsnkYWCq6i6sxSgieT+Wvx3wVh5J069ZTpkLWAQLNCOOW8VBXF027SOVVN4042rAZmw2zW0DDx0rkZAby2mAbvcXfy0tlXtCwmCIkOxN6S/ApLm5kbQVs+lwRKg=
notifications:
  slack:
    secure: JzdsoRPzirozD5vkJpneYVi6Dx4JH72/LtwcNP7ckOrhYDsrE1E/hQvlBCIW84D8/uG4sZKnkB9JP4NocOa3f3INspbiawxFOSPsvIP8HFOdkvrYQdSW7kO0867EHxSfGgq1b34OwdHfLcvn1saPpj8NPv36Hg9y5KzclaeWWZM=
